#!/usr/bin/env python3
"""
build_samplelib.py -- render the sound library.

The library is *generated*, not downloaded, which is what makes it safe to
redistribute: every sample in samplelib/ is an original recording of a
physical model written in this repo, so it is free of any third party
copyright and can be published under CC0.

    python3 tools/build_samplelib.py --all
    python3 tools/build_samplelib.py --pack piano --rr 2 --every 3

Packs are stored as 16-bit FLAC + a manifest.json the sampler reads.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import time

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "src"))

import numpy as np  # noqa: E402
import soundfile as sf  # noqa: E402

from sonora import core as C  # noqa: E402
from sonora.instruments import strings as S, keys as K, synth as Y, guitar as G, voice as V, world as W  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
LIB = os.path.join(HERE, "..", "samplelib")

# pack -> (render function, note range, base duration, mode, kwargs)
PACKS = {
    "piano": (K.piano, (36, 96), 6.0, "oneshot", {}),
    "felt_piano": (K.felt_piano, (48, 84), 5.0, "oneshot", {}),
    "rhodes": (K.rhodes, (40, 88), 4.0, "oneshot", {}),
    "violin": (S.bowed, (55, 91), 4.0, "loop", dict(players=1, body="violin")),
    "violin_section": (lambda m, d, **k: S.section([m], d, size=8, body="violin", **k),
                       (55, 91), 4.0, "loop", {}),
    "cello": (lambda m, d, **k: S.bowed(m, d, body="cello", players=1, **k),
              (36, 72), 4.0, "loop", {}),
    "guitar_steel": (G.steel, (40, 76), 4.0, "oneshot", {}),
    "guitar_nylon": (G.nylon, (40, 76), 4.0, "oneshot", {}),
    "harp": (S.harp_note, (36, 88), 4.0, "oneshot", {}),
    "flute": (W.flute, (60, 96), 2.5, "loop", {}),
    "choir_ah": (lambda m, d, **k: V.vowel(m, d, "ah", **k), (48, 84), 4.0, "loop", {}),
    "choir_oo": (lambda m, d, **k: V.vowel(m, d, "oo", **k), (48, 84), 4.0, "loop", {}),
    "kalimba": (W.kalimba, (60, 96), 3.0, "oneshot", {}),
    "handpan": (W.handpan, (48, 79), 4.0, "oneshot", {}),
    "glock": (lambda m, d, **k: K.bell(m, d, kind="glock", **k), (72, 108), 3.0, "oneshot", {}),
}


def render_pack(name: str, every: int = 3, rr: int = 2, sr: int = 48000,
                root: str = LIB, quiet: bool = False) -> dict:
    fn, (lo, hi), dur, mode, kw = PACKS[name]
    out_dir = os.path.join(root, name)
    os.makedirs(out_dir, exist_ok=True)
    notes = []
    t0 = time.time()
    for midi in range(lo, hi + 1, every):
        for v in range(rr):
            y = fn(midi, dur, seed=midi * 31 + v * 7, **kw)
            y = np.asarray(y, dtype=np.float32)
            if y.ndim == 2:
                y = y.mean(axis=1)
            y = C.fade(y, 0.003, 0.05 if mode == "oneshot" else 0.15)
            fname = f"{name}_{midi:03d}_rr{v}.flac"
            sf.write(os.path.join(out_dir, fname), np.clip(y, -1, 1), sr,
                     subtype="PCM_16")
            entry = dict(midi=midi, file=fname, dur=float(len(y) / sr), rr=v)
            if mode == "loop":
                # loop the steady part: 35%..85% of the note, crossfaded
                entry["loop"] = [round(0.35 * len(y) / sr, 3), round(0.85 * len(y) / sr, 3)]
            notes.append(entry)
    manifest = dict(name=name, sr=sr, mode=mode, every=every, rr=rr,
                    range=[lo, hi], notes=notes,
                    license="CC0-1.0 (generated by sonora, no third party material)",
                    generator=f"sonora {name} physical/modelling synthesiser")
    with open(os.path.join(out_dir, "manifest.json"), "w") as f:
        json.dump(manifest, f, indent=1)
    if not quiet:
        size = sum(os.path.getsize(os.path.join(out_dir, n["file"])) for n in notes) / 1e6
        print(f"  {name:16s} {len(notes):4d} samples  {size:6.2f} MB  ({time.time()-t0:.1f}s)")
    return manifest


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--all", action="store_true")
    ap.add_argument("--pack", action="append", default=[])
    ap.add_argument("--every", type=int, default=3, help="semitones between sampled notes")
    ap.add_argument("--rr", type=int, default=2, help="round robin variants")
    ap.add_argument("--sr", type=int, default=48000)
    ap.add_argument("--root", default=LIB)
    args = ap.parse_args()

    names = list(PACKS) if args.all else (args.pack or ["piano"])
    C.SR = args.sr
    print(f"building sample library -> {os.path.abspath(args.root)}")
    index = {}
    for n in names:
        if n not in PACKS:
            print(f"  unknown pack {n}; known: {', '.join(PACKS)}")
            continue
        index[n] = render_pack(n, args.every, args.rr, args.sr, args.root)
    with open(os.path.join(args.root, "index.json"), "w") as f:
        json.dump({k: {kk: vv for kk, vv in v.items() if kk != "notes"}
                   for k, v in index.items()}, f, indent=1)
    print("done.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
